package org.example.rpcProtocol;

public enum ResponseType
{
    OK, ERROR, LOGIN, LOGOUT, GET_USER_BY_USERNAME, GET_ALL_CURSE, GENEREAZA_LISTA_LOCURI, CAUTA_CURSA, GET_NR_LOCURI_LIBERE_CURSA, REZERVARE;
}
